import { Types } from 'mongoose';
import { SessionStatus, SessionType } from '../../../definitions';
import { SessionModelClass } from '../../../database';
import { IBaseEntity } from '../base';
export declare class Session implements IBaseEntity<Session, SessionModelClass> {
    protected _id?: Types.ObjectId;
    protected _ownerId?: Types.ObjectId;
    protected _type?: SessionType;
    protected _accessToken?: string;
    protected _useragent?: string;
    protected _expires?: number;
    protected _status?: SessionStatus;
    protected _usedAt?: Date;
    protected _expiresAt?: Date;
    protected _updatedAt?: Date;
    protected _createdAt?: Date;
    buildId(id: Types.ObjectId): Session;
    buildOwnerId(ownerId: Types.ObjectId): Session;
    buildType(type: SessionType): Session;
    buildAccessToken(accessToken: string): Session;
    buildUseragent(useragent: string): Session;
    buildExpires(expires: number): Session;
    buildStatus(status: SessionStatus): Session;
    buildUsedAt(usedAt: Date): Session;
    buildExpiresAt(expiresAt: Date): Session;
    buildUpdatedAt(updatedAt: Date): Session;
    buildCreatedAt(createdAt: Date): Session;
    getOwnerId(): Types.ObjectId;
    getType(): SessionType;
    getAccessToken(): string;
    getUseragent(): string;
    getExpires(): number;
    getStatus(): SessionStatus;
    getId(): Types.ObjectId;
    getUsedAt(): Date;
    getExpiresAt(): Date;
    getCreatedAt(): Date;
    getUpdatedAt(): Date;
    convertToEntity(session: SessionModelClass): Session;
    convertToModelClass(): SessionModelClass;
}
